# This file was generated by GoReleaser. DO NOT EDIT.
cask "run-mcp" do
  name "run-mcp"
  desc "A fast, portable, single-binary security scanner for the Model Context Protocol (MCP)."
  homepage "https://github.com/ensigniasec/run-mcp"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "run-mcp"

  on_macos do
    on_intel do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Darwin_x86_64.tar.gz"
      sha256 "40e58ac4c42c60f7eb5959ad9e2a2f3f2f7f77c77d668311fc82d6458a3c1f09"
    end
    on_arm do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Darwin_arm64.tar.gz"
      sha256 "d5b1335c2a7b481d09cc610a83c30b01d4c4230b793ca78627c55e3ad6a9e286"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Linux_x86_64.tar.gz"
      sha256 "e9bcec67699d4a217cfe91317335e6a7067daab2545fa6f7f79f2fb217ae6dc6"
    end
    on_arm do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Linux_arm64.tar.gz"
      sha256 "9351c2ad55ab2a68f6dae228ab66b60db30fefa327f9321471ffd3892a4555e7"
    end
  end

  uninstall delete: [
      "~/.run-mcp/results.json",
      "~/.run-mcp",
    ]

  # No zap stanza required
end
