# This file was generated by GoReleaser. DO NOT EDIT.
cask "run-mcp" do
  name "run-mcp"
  desc "A fast, portable, single-binary security scanner for the Model Context Protocol (MCP)."
  homepage "https://github.com/ensigniasec/run-mcp"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "run-mcp"

  on_macos do
    on_intel do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Darwin_x86_64.tar.gz"
      sha256 "c77fca171769342f3642d19cf443dfc65c4cb3d520016468257ae5d6a8276d5b"
    end
    on_arm do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Darwin_arm64.tar.gz"
      sha256 "a25a13025a014b7e1f1c5f79b9c6b9979a583a8e4a5450a630a884cb80a286aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Linux_x86_64.tar.gz"
      sha256 "0793735d2f577e7fed8cf79505ef9cabd0056cf2e770d18694a1e50effb50f00"
    end
    on_arm do
      url "https://github.com/ensigniasec/run-mcp/releases/download/v#{version}/run-mcp_Linux_arm64.tar.gz"
      sha256 "6f494948394290ba0ccbe38fa506dc78b4141f66a8cbe31a653ff9ce945859f1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/run-mcp"], sudo: true
    end
  end

  uninstall delete: [
      "~/.run-mcp/results.json",
      "~/.run-mcp",
      "~/Library/Application Support/run-mcp",
      "~/Library/Application Support/run-mcp/results.json",
    ]

  # No zap stanza required
end
